# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Boyuu AI Lab"
title:              "Boyuu AI Lab"
description:        "Boyuu AI Lab is dedicated to researching cutting-edge AI technologies"


# URL
url:                https://boyuu-ai.github.io
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "news"
    href:           "/news"
  # - name:           "research"
  #   href:           "/research"
  # - name:           "publications"
  #   href:           "/publication"
  # - name:           "people"
  #   href:           "/people"
#  - name:           "blog"
#    href:           "/blog"
#  - name:           "resources"
#    href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
